spring:
  application:
    name: inventory-service
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:commerce_platform}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:vincent}
    password: ${DB_PASSWORD:1q2w3e4R}
    hikari:
      pool-name: InventoryServiceHikariPool
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: ${SERVER_PORT:8082}

app:
  jwt:
    issuer: ${JWT_ISSUER:auth-service}
    public-key-path: ${JWT_PUBLIC_KEY_PATH:file:../devops/data/keys/public.pem}
    public-key-fallback-paths:
      - file:devops/data/keys/public.pem
      - file:../devops/data/keys/public.pem
  inventory:
    cache-ttl: PT30M
    idempotency-ttl: PT24H
    lock-ttl: PT10S
    local-cache-ttl: PT30S
    ttl-jitter-max-seconds: 60
    hot-product-codes:
      - IPHONE17
      - RTX5090
      - PS6
  kafka:
    max-retries: 3
    retry-interval-ms: 1000
    topics:
      order-created: order-created
      inventory-reserved: inventory-reserved
      inventory-failed: inventory-failed
      inventory-dlq: inventory-dlq

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
