apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  SERVER_PORT: "8088"
  SPRING_PROFILES_ACTIVE: "k8s"
  JWT_PUBLIC_KEY_PATH: "file:/app/keys/public.pem"
  JWT_ISSUER: "auth-service"
  PRODUCT_SERVICE_URI: "http://product-service:80"
  INVENTORY_SERVICE_URI: "http://inventory-service:80"
  ORDER_SERVICE_URI: "http://order-service:80"
