apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: inventory-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: inventory-service-config
            - secretRef:
                name: auth-service-secret
          volumeMounts:
            - name: jwt-keys
              mountPath: /app/keys
              readOnly: true
          readinessProbe:
            httpGet:
              path: /api/inventory/health
              port: 8082
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/inventory/health
              port: 8082
            initialDelaySeconds: 45
            periodSeconds: 20
      volumes:
        - name: jwt-keys
          secret:
            secretName: auth-service-jwt-keys
