{{- if .Values.services.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: {{ include "commerce-platform.namespace" . }}
  labels:
    {{- include "commerce-platform.serviceLabels" (dict "root" . "appName" "gateway-service") | nindent 4 }}
spec:
  replicas: {{ .Values.services.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "commerce-platform.selectorLabels" (dict "root" . "appName" "gateway-service") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "commerce-platform.selectorLabels" (dict "root" . "appName" "gateway-service") | nindent 8 }}
    spec:
      containers:
        - name: gateway-service
          image: {{ include "commerce-platform.image" .Values.services.gateway.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.gateway.containerPort }}
          envFrom:
            - configMapRef:
                name: gateway-service-config
            - secretRef:
                name: {{ .Values.secrets.dbSecretName }}
          volumeMounts:
            - name: jwt-keys
              mountPath: /app/keys
              readOnly: true
          readinessProbe:
            httpGet:
              path: {{ .Values.services.gateway.probes.path }}
              port: {{ .Values.services.gateway.containerPort }}
            initialDelaySeconds: {{ .Values.services.gateway.probes.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.services.gateway.probes.readinessPeriodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.services.gateway.probes.path }}
              port: {{ .Values.services.gateway.containerPort }}
            initialDelaySeconds: {{ .Values.services.gateway.probes.livenessInitialDelaySeconds }}
            periodSeconds: {{ .Values.services.gateway.probes.livenessPeriodSeconds }}
      volumes:
        - name: jwt-keys
          secret:
            secretName: {{ .Values.secrets.jwtKeysSecretName }}
{{- end }}
