{{- if .Values.services.inventory.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: {{ include "commerce-platform.namespace" . }}
  labels:
    {{- include "commerce-platform.serviceLabels" (dict "root" . "appName" "inventory-service") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "commerce-platform.selectorLabels" (dict "root" . "appName" "inventory-service") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.services.inventory.servicePort }}
      targetPort: {{ .Values.services.inventory.containerPort }}
{{- end }}
