apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: auth-service-secret
          volumeMounts:
            - name: jwt-keys
              mountPath: /app/keys
              readOnly: true
          readinessProbe:
            httpGet:
              path: /api/v1/products/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/products/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 20
      volumes:
        - name: jwt-keys
          secret:
            secretName: auth-service-jwt-keys
