apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  SERVER_PORT: "8083"
  SPRING_PROFILES_ACTIVE: "k8s"
  JWT_PUBLIC_KEY_PATH: "file:/app/keys/public.pem"
  DB_HOST: "host.minikube.internal"
  DB_PORT: "3306"
  DB_NAME: "commerce_platform"
  REDIS_HOST: "host.minikube.internal"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "host.minikube.internal:9092"
  JWT_ISSUER: "auth-service"
