server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: gateway-service
  profiles:
    default: local
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

app:
  jwt:
    issuer: ${JWT_ISSUER:auth-service}
    public-key-path: ${JWT_PUBLIC_KEY_PATH:file:../devops/data/keys/public.pem}
    public-key-fallback-paths:
      - file:devops/data/keys/public.pem
      - file:../devops/data/keys/public.pem
  routes:
    product-uri: ${PRODUCT_SERVICE_URI:http://localhost:8081}
    inventory-uri: ${INVENTORY_SERVICE_URI:http://localhost:8082}
    order-uri: ${ORDER_SERVICE_URI:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLE_PROBABILITY:1.0}
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] [%X{traceId:-}] %logger{36} - %msg%n"
